### PR TITLE
InteractionID & Count Explainer

### PR DESCRIPTION
**Pull request by zuoaoyuan**
Add an explainer for interactionId & Count.

### CODE REVIEW

**Comment by mmocny** [comment]
I like the latest explainer.  I made some updates directly to your readme.  I tried to submit as a PR so you can see a nice diff, but there was an error and I was able to just push a change directly into your branch.  You can [see the diff](https://github.com/w3c/event-timing/pull/133/commits/d956e62805eeee0c20686c7c0f0b04d4f8262c3f).

LGTM!

**Comment by mmocny** [comment]
Regarding the CI build issue, its based on the actual spec build, not this readme.

See this error:
Screenshot 2023-10-26 at 16 07 57

We may want to try to fix that.

**Comment by mmocny** [comment]
Here is the line that is breaking the build: https://github.com/w3c/event-timing/commit/7fa8ac5661a16de03415911113aee337f7764049

Indeed, it seems to have a missing attribute value.  I will file a separate spec issue.

**Comment by zuoaoyuan** [comment]
@mmocny The updates looks great! And thanks for digging into the build issue.

**Review by mmocny — APPROVED** [review]
LGTM with the one remaining comment at the bottom, to update the code snippet just a bit.

**Review by mmocny — APPROVED** [review]

**Comment by mmocny** [comment]
I merged this in, but it didn't automatically squash the commits.  I'm so accustomed to this being the default option, that I forgot to look for it.  (It just means we have a few extra commits in git history, I wouldn't bother re-writting main branch to fix this).

I think we can change this in the github project settings for next time.

**Comment by mmocny** [comment]
Hmm, I don't have access to settings for the repo, and it may even be explicitly disabled as an option for merge... Some docs references:

[How to squash merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-commits)
[Configure repo for squashing prs](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests)

**Pull request merged**
